DELIMITER ;
INSERT INTO `ds` (`table_name`, `title`, `reorderfield`, `use_history`, `searchfield`, `displayfield`, `sortfield`, `searchany`, `hint`, `overview_tpl`, `sync_table`, `writetable`, `globalsearch`, `listselectionmodel`, `sync_view`, `syncable`, `cssstyle`, `alternativeformxtype`, `read_table`, `class_name`, `special_add_panel`, `existsreal`, `character_set_name`, `read_filter`, `listxtypeprefix`, `phpexporter`, `phpexporterfilename`, `combined`, `default_pagesize`, `allowForm`, `listviewbaseclass`, `showactionbtn`, `modelbaseclass`) VALUES ('dashboard','Dashboard','position',NULL,'title','title','title',NULL,NULL,NULL,NULL,NULL,NULL,'rowmodel',NULL,NULL,NULL,NULL,'view_readttable_dashboard','Dashboard',NULL,1,NULL,NULL,NULL,'XlsxWriter','dashboard {DATE} {TIME}',0,1000,1,'Tualo.DataSets.ListView',1,'Tualo.DataSets.model.Basic') ON DUPLICATE KEY UPDATE title=VALUES(title), reorderfield=VALUES(reorderfield), use_history=VALUES(use_history), searchfield=VALUES(searchfield), displayfield=VALUES(displayfield), sortfield=VALUES(sortfield), searchany=VALUES(searchany), hint=VALUES(hint), overview_tpl=VALUES(overview_tpl), sync_table=VALUES(sync_table), writetable=VALUES(writetable), globalsearch=VALUES(globalsearch), listselectionmodel=VALUES(listselectionmodel), sync_view=VALUES(sync_view), syncable=VALUES(syncable), cssstyle=VALUES(cssstyle), alternativeformxtype=VALUES(alternativeformxtype), read_table=   VALUES(read_table), class_name=VALUES(class_name), special_add_panel=VALUES(special_add_panel), existsreal=VALUES(existsreal), character_set_name=VALUES(character_set_name), read_filter=VALUES(read_filter), listxtypeprefix=VALUES(listxtypeprefix), phpexporter=VALUES(phpexporter), phpexporterfilename=VALUES(phpexporterfilename), combined=VALUES(combined), default_pagesize=VALUES(default_pagesize), allowForm=VALUES(allowForm), listviewbaseclass=VALUES(listviewbaseclass), showactionbtn=VALUES(showactionbtn), modelbaseclass=VALUES(modelbaseclass);
INSERT  IGNORE INTO `ds_column` (`table_name`, `column_name`, `default_value`, `default_max_value`, `default_min_value`, `update_value`, `is_primary`, `syncable`, `referenced_table`, `referenced_column_name`, `is_nullable`, `is_referenced`, `writeable`, `note`, `data_type`, `column_key`, `column_type`, `character_maximum_length`, `numeric_precision`, `numeric_scale`, `character_set_name`, `privileges`, `existsreal`, `deferedload`, `hint`, `fieldtype`) VALUES ('dashboard','classname',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,0,NULL,'varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('dashboard','configuration','{}',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'longtext','','longtext',4294967295,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('dashboard','dashboard_type',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','MUL','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('dashboard','id','{:uuid()}',NULL,NULL,NULL,1,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','PRI','varchar(36)',36,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('dashboard','position',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('dashboard','title',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,'');
INSERT  IGNORE INTO `ds_column_list_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `editor`, `position`, `summaryrenderer`, `renderer`, `summarytype`, `hidden`, `active`, `filterstore`, `grouped`, `flex`, `direction`, `align`, `listfiltertype`, `hint`) VALUES ('dashboard','classname','DE','Klasse','gridcolumn',NULL,3,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('dashboard','configuration','DE','Konfiguration','gridcolumn',NULL,4,'','','',1,1,'',0,1.00,'ASC','left','',NULL),
('dashboard','dashboard_type','DE','Typ','column_dashboard_available_types_xtype',NULL,1,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('dashboard','id','DE','ID','gridcolumn',NULL,0,'','','',1,1,'',0,1.00,'ASC','left','',NULL),
('dashboard','position','DE','Position','gridcolumn',NULL,5,'','','',1,1,'',0,1.00,'ASC','left','',NULL),
('dashboard','title','DE','Titel','gridcolumn',NULL,2,'','','',0,1,'',0,1.00,'ASC','left','',NULL);
INSERT  IGNORE INTO `ds_column_form_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `field_path`, `position`, `hidden`, `active`, `allowempty`, `fieldgroup`, `flex`, `hint`) VALUES ('dashboard','classname','DE','Klasse','displayfield','Allgemein/Angaben',3,0,1,NULL,NULL,NULL,'\'\''),
('dashboard','configuration','DE','Konfiguration','tualocodejson','Allgemein/Erweitert',4,0,1,NULL,NULL,NULL,'\'\''),
('dashboard','dashboard_type','DE','Typ','combobox_dashboard_available_types_xtype','Allgemein/Angaben',1,0,1,NULL,NULL,NULL,'\'\''),
('dashboard','id','DE','ID','displayfield','Allgemein/Angaben',0,0,1,NULL,NULL,NULL,'\'\''),
('dashboard','position','DE','Position','displayfield','Allgemein/Erweitert',5,0,1,NULL,NULL,NULL,'\'\''),
('dashboard','title','DE','Titel','textfield','Allgemein/Angaben',2,0,1,NULL,NULL,NULL,'\'\'');
INSERT  IGNORE INTO `ds_reference_tables` (`table_name`, `reference_table_name`, `columnsdef`, `constraint_name`, `active`, `searchable`, `autosync`, `position`, `path`, `existsreal`, `tabtitle`) VALUES ('dashboard','available_dashboards','{\"dashboard_type\":\"xtype\"}','dashboard_type_fk',0,0,0,999,'',1,'');
INSERT  IGNORE INTO `ds_access` (`role`, `table_name`, `read`, `write`, `delete`, `append`, `existsreal`) VALUES ('administration','dashboard',1,1,1,1,NULL),
('_default_','dashboard',1,NULL,NULL,NULL,NULL);
